trigger:
  branches:
    include:
      - master

pool: Default

variables:
  ACR_LOGIN_SERVER: zzeydwqgimagescanacr.azurecr.io
  IMAGE_NAME: 'sampleapp'
  IMAGE_TAG: 'latest'
  SCANNER_TOOL_PATH: '/usr/local/bin/trivy'  # Adjust this if using a different scanner

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        steps:
          # Build and push the Docker image to the registry
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-service-con'   # Use your Docker Registry service connection name
              repository: '$(IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(IMAGE_TAG)

  - stage: ScanImage
    dependsOn: BuildAndPush
    jobs:
      - job: Scan
        steps:
          - script: |
              echo "Installing Trivy..."
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
              echo "Trivy installed successfully:"
              trivy --version
            displayName: 'Install Trivy'
          
          - script: |
              echo "Scanning the image with Trivy..."
              $SCANNER_TOOL_PATH image $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG 
              $SCANNER_TOOL_PATH image $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG > scan_report.txt
            displayName: 'Run Image Scan'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'scan_report.txt'
              artifactName: 'SecurityReports'
            displayName: 'Publish Scan Report'
