- stage: ReviewScanResults
  dependsOn: ScanImage
  jobs:
    - job: EvaluateScan
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifactName: 'SecurityReports'
            targetPath: '$(Pipeline.Workspace)/SecurityReports'  # Store in a known location
          displayName: 'Download Scan Report Artifact'
        
        - script: |
            echo "Listing contents of $(Pipeline.Workspace)/SecurityReports..."
            ls -la $(Pipeline.Workspace)/SecurityReports
          displayName: 'Verify Scan Report Download'
        
        - script: |
            echo "Checking for critical or high vulnerabilities..."
            ls -la
            critical=$(grep -i "CRITICAL" $(Pipeline.Workspace)/SecurityReports/scan_report.txt | wc -l)
            high=$(grep -i "HIGH" $(Pipeline.Workspace)/SecurityReports/scan_report.txt | wc -l)
            echo $critical
            echo $high
            if [ "$critical" -gt 0 ] || [ "$high" -gt 0 ]; then
              echo "Critical or high vulnerabilities found. Failing pipeline."
              exit 1
            else
              echo "No critical or high vulnerabilities found. Approved for deployment."
            fi
          displayName: 'Evaluate Scan Report'
