trigger:
  branches:
    include:
      - master

pool: Default

variables:
  ACR_LOGIN_SERVER: zzeydwqgimagescanacr.azurecr.io
  IMAGE_NAME: 'sampleapp'
  IMAGE_TAG: 'latest'
  SCANNER_TOOL_PATH: '/usr/local/bin/trivy'  # Adjust this if using a different scanner

stages:
  - stage: BuildAndPush
    jobs:
      - job: Build
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'docker-service-con'  # Name of the managed identity service connection
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into Azure Container Registry..."
                az acr login --name $(ACR_LOGIN_SERVER)

          - task: Docker@2
            inputs:
              containerRegistry: $(ACR_LOGIN_SERVER)
              repository: $(IMAGE_NAME)
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(IMAGE_TAG)

