trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_LOGIN_SERVER: 'zzeydwqgimagescanacr.azurecr.io'
  IMAGE_NAME: 'sampleapp'
  IMAGE_TAG: 'latest'
  SCANNER_TOOL_PATH: '/usr/local/bin/trivy'

stages:

  - stage: ScanImage
    jobs:
      - job: Scan
        steps:
          - script: |
              echo "Installing Trivy..."
              curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
              echo "Trivy installed successfully:"
              trivy --version
              echo "Scanning the image with Trivy..."
              $SCANNER_TOOL_PATH image $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG > scan_report.txt
            displayName: 'Run Image Scan'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'scan_report.txt'
              artifactName: 'SecurityReports'
            displayName: 'Publish Scan Report'


